const products = [
  {
    id: 1,
    name: "Apple iPhone",
    price: 79999,
    category: "Mobiles",
    image: "/Images/Apple iPhone.jpg",
    description: "Latest Apple iPhone with powerful performance and advanced camera.",
    rating: 4.6,
    reviews: 2450,
    purchased: "1K+ bought this month",
  },
  {
    id: 2,
    name: "Apple iPhone Pro",
    price: 89999,
    category: "Mobiles",
    image: "/Images/AppleIphone.jpg",
    description: "Premium iPhone Pro with high quality display and camera.",
    rating: 4.7,
    reviews: 1800,
    purchased: "900+ bought this month",
  },
  {
    id: 3,
    name: "iPhone 17",
    price: 99999,
    category: "Mobiles",
    image: "/Images/iphone_17.jpg",
    description: "New generation smartphone with advanced features.",
    rating: 4.8,
    reviews: 3200,
    purchased: "2K+ bought this month",
  },
  {
    id: 4,
    name: "Floral Perfume",
    price: 1499,
    category: "Perfumes",
    image: "/Images/FloralPerfume.jpg",
    description: "Fresh floral fragrance for everyday use.",
    rating: 4.4,
    reviews: 850,
    purchased: "500+ bought this month",
  },
  {
    id: 5,
    name: "Perfumes",
    price: 1299,
    category: "Perfumes",
    image: "/Images/Perfumes.jpg",
    description: "Long lasting perfume with attractive fragrance.",
    rating: 4.3,
    reviews: 700,
    purchased: "400+ bought this month",
  },
  {
    id: 6,
    name: "Unique Body Mist Perfume",
    price: 999,
    category: "Perfumes",
    image: "/Images/UniqueBodymistperfume.jpg",
    description: "Refreshing body mist with long lasting smell.",
    rating: 4.5,
    reviews: 950,
    purchased: "800+ bought this month",
  },

  {
    id: 7,
    name: "Lakme Moisturizer & Color Transform Cream",
    price: 599,
    category: "Beauty",
    image: "/Images/lakme-moisturizer-and-color-transform-cream.webp",
    description: "Moisturizing cream for glowing and healthy skin.",
    rating: 4.4,
    reviews: 1200,
    purchased: "1K+ bought this month",
  },

  {
    id: 8,
    name: "Skin Brightening Cream",
    price: 499,
    category: "Beauty",
    image: "/Images/SkinBrightening cream.webp",
    description: "Skin brightening cream for daily skincare routine.",
    rating: 4.2,
    reviews: 600,
    purchased: "300+ bought this month",
  },

  {
    id: 9,
    name: "Pink Watch",
    price: 2499,
    category: "Watches",
    image: "/Images/PinkWatch.jpg",
    description: "Stylish pink watch for women.",
    rating: 4.5,
    reviews: 900,
    purchased: "700+ bought this month",
  },

  {
    id: 10,
    name: "Smart Watch",
    price: 3499,
    category: "Watches",
    image: "/Images/SmartWatch.jpg",
    description: "Smart watch with fitness and health features.",
    rating: 4.6,
    reviews: 1500,
    purchased: "1K+ bought this month",
  },

  {
    id: 11,
    name: "Smart Watch 1",
    price: 3999,
    category: "Watches",
    image: "/Images/SmartWatch1.jpg",
    description: "Modern smartwatch with premium design.",
    rating: 4.3,
    reviews: 800,
    purchased: "500+ bought this month",
  },

  {
    id: 12,
    name: "Sports Shoes",
    price: 1999,
    category: "Footwear",
    image: "/Images/SportsShoes.jpg",
    description: "Comfortable sports shoes for running and walking.",
    rating: 4.5,
    reviews: 1400,
    purchased: "1K+ bought this month",
  },

  {
    id: 13,
    name: "Sports Shoes 1",
    price: 2299,
    category: "Footwear",
    image: "/Images/SportsShoes1.jpg",
    description: "Lightweight sports shoes with comfortable fit.",
    rating: 4.4,
    reviews: 900,
    purchased: "600+ bought this month",
  },

  {
    id: 14,
    name: "Sports Shoes 2",
    price: 2599,
    category: "Footwear",
    image: "/Images/SportShoes2.jpg",
    description: "Durable shoes suitable for daily activities.",
    rating: 4.3,
    reviews: 750,
    purchased: "400+ bought this month",
  },

  {
    id: 15,
    name: "Women T-Shirt",
    price: 799,
    category: "Fashion",
    image: "/Images/WomenTshirt.jpg",
    description: "Comfortable stylish t-shirt for women.",
    rating: 4.6,
    reviews: 1100,
    purchased: "900+ bought this month",
  },
];

export default products;